### ISSUE TITLE
Class not found raises NullPointerException

### ISSUE THREAD

**Issue by jdomenechb** [briandilley/jsonrpc4j#165]
In [this line](https://github.com/briandilley/jsonrpc4j/blob/master/src/main/java/com/googlecode/jsonrpc4j/DefaultExceptionResolver.java#L37), in the case that the Java class for the Exception is not found, a _null_ is returned (see [this line](https://github.com/briandilley/jsonrpc4j/blob/master/src/main/java/com/googlecode/jsonrpc4j/DefaultExceptionResolver.java#L71)) and a NullPointerException is raised that does not provide any information on the server exception.

The code should be modified tom in that case, provide the generic
throwable. For example:

```
[...]
String message = hasNonNullTextualData(dataObject, JsonRpcBasicServer.ERROR_MESSAGE) ? dataObject.get(JsonRpcBasicServer.ERROR_MESSAGE).asText() : null;
		
Throwable throwable = createThrowable(exceptionTypeName, message);

if (throwable == null) {
	logger.warn("Unable to create throwable");
	return createJsonRpcClientException(errorObject);
}

return throwable;
[...]
```

**Comment by yin** [comment]
Hello @jdomenechb, 

I think a better way would be to thor the ClassNotFoundException from this [catch-clause](https://github.com/briandilley/jsonrpc4j/blob/master/src/main/java/com/googlecode/jsonrpc4j/DefaultExceptionResolver.java#L101).

It will bubble-up the call-stack, printing correct problem, source line or could be handled. In the end it is the root cause and being unchecked there is little need, nor benefit, from the situation up in more edge-cases. Would this work for you?

**Comment by jdomenechb** [comment]
Works for me, but I still have the need to provide the user the error message coming from the server, I will be following #166 closely, as such a solution would solve my problem.

Thanks for the fast resolution of the bug.

**Comment by yin** [comment]
@jdomenechb see #166
