### ISSUE TITLE
How to define a Lambda as function parameter ?

### ISSUE THREAD

**Issue by xuyuanxiang** [briandilley/jsonrpc4j#182]
How to implement this:

```java
@JsonRpcService("rpc/test")
public interface TestService {

    public interface Thunk {
        int doSomething(Map context);
    }

    void process(Thunk thunk);
}
```

and  how to call it:

```json
{
    "method":"process",
    "id": "0",
    "jsonrpc": "2.0",
    "params":[]
}
```

**Comment by mslipper** [comment]
Hi @xuyuanxiang,

This isn't something that this library supports nor is it an implementation that I recommend. Unless you're really careful, you're opening yourself up to remote code execution attacks. 

If you really want to do this, you can create a Jackson serde manually in order to parse the `Thunk` object's wire format.
