### ISSUE TITLE
Document how to use with Spring Boot

### ISSUE THREAD

**Issue by msgilligan** [briandilley/jsonrpc4j#69]
I'm trying to use **jsonrpc4j** with Spring Boot and having some trouble. I'm still debugging, but it would be great if the README would have a section on correct usage with Spring Boot.

**Comment by msgilligan** [comment]
I got it working by adding the following methods to a `@Configuration` class:

    @Bean
    public BitcoinJsonRpc bitcoinRPCService(PeerService peerService) {
        return new BitcoinJsonRpcImpl(peerService);
    }

    @Bean(name="/bitcoin-rpc")
    public JsonServiceExporter bitcoinServiceExporter(BitcoinJsonRpc bitcoinJsonRPCService) {
        JsonServiceExporter exporter = new JsonServiceExporter();
        exporter.setService(bitcoinJsonRPCService);
        exporter.setServiceInterface(BitcoinJsonRpc.class);
        return exporter;
    }

I was not able to get it working with the `JsonRpcService` annotation and `AutoJsonRpcServiceExporter`,  and after a small amount of debugging switched to the above approach.

**Comment by davidnewcomb** [comment]
I have just spent all evening fighting this. jsonrpc4j pulls in as a dependency jackson 2.0.2. Spring Boot pulls in jackson 2.4.6. Spring Boot calls databind/ObjectMapper which now lives in jackson-databind. Unfortunately the classpath is constructed so that the 2.0.2 version is reached first and you get the following message before your container blows up :(

Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.registerModules(Ljava/lang/Iterable;)Lcom/fasterxml/jackson/databind/ObjectMapper;

If you remove the 2.0.2 jars then it seems to work but the pom keeps bringing them in again.

My work around was to alter the pom.xml to remove the dependency but really we need a new release of jsonrpc which doesn't depend on the old version of jackson.

		<dependency>
			<groupId>com.github.briandilley.jsonrpc4j</groupId>
			<artifactId>jsonrpc4j</artifactId>
			<version>1.1</version>
			<exclusions>
				<exclusion>
					<artifactId>jackson-core</artifactId>
					<groupId>com.fasterxml.jackson.core</groupId>
				</exclusion>
				<exclusion>
					<artifactId>jackson-databind</artifactId>
					<groupId>com.fasterxml.jackson.core</groupId>
				</exclusion>
			</exclusions>
		</dependency>

**Comment by gaborbernat** [comment]
Already started it, trying to get release rights from the repository owner
:)

**Comment by msgilligan** [comment]
Thanks @davidnewcomb. I may give that a try.

My alternate (above) solution is now on Github (along with the full project): [BitcoinConfig.java#L45-L56](https://github.com/msgilligan/bitcoinj-addons/blob/master/src/main/java/com/msgilligan/bitcoinj/spring/config/BitcoinConfig.java#L45-L56)

**Comment by spith** [comment]
Is this issue solved? I am facing same issue and do not want to alter my existing code that uses jsonrpc4j?

**Comment by aol-nnov** [comment]
@msgilligan I know, it's been awhile since last log record here, but I've stumbled upon it and found a way making ```AutoJsonRpcServiceExporter``` to work (YMMV though):

1) create  ```AutoJsonRpcServiceExporter``` bean
2) annotate your service interface with ```@JsonRpcService("/path/to/endpoint")```
3) annotate your service implementation with ```@Service```
And it works! :) (tested with spring boot 1.3.2.RELEASE and jsonrpc4j 1.2.0)

P.S.: if anyone knows how to create composite service using annotations only, your advice is highly appreciated!

**Comment by gaborbernat** [comment]
@aol-nnov I started to refactor the code for avoiding duplicity, easier extensiblity and better tests at https://github.com/gaborbernat/jsonrpc4j, CI integration and so on; once done will look more in depth into this and come up with a solution. Also managed to get my hands on a JCenter release rights, so we can release new versions of the library without the presence of @briandilley, automatically.

**Comment by aol-nnov** [comment]
@gaborbernat glad to hear!
Currently I'm rolling my first spring project and when I wrap my head around all this stuff, hopefully, I will contribute something here too :)

**Comment by Shmarkus** [comment]
A basic example how to get things going with Spring Boot can be found on the wiki pages here!
